// Generated by `aurorality swiftgen` — do not edit by hand.
import SwiftUI

struct HyperChatGeneratedView: View {
    let context: HyperChatContext
    let eventSink: (String) -> Void

    var body: some View {
        NavigationSplitView {
            List {
                Section {
                    Button {
                        eventSink("newConversation")
                    } label: {
                            HStack(alignment: .top, spacing: 4) {
                                Image(systemName: "plus")
                                Text("New")
                            }
                    }
            .buttonStyle(.bordered)
                    ForEach(Array(context.conversations.enumerated()), id: \.offset) { _, conv in
                            Button {
                                eventSink("selectConversation:\(conv.id)")
                            } label: {
                                    VStack(alignment: .leading, spacing: 4) {
                                        Text(String(describing: conv.title))
            .font(.callout)
            .fontWeight(.semibold)
                                        Text(String(describing: conv.subtitle))
            .font(.caption)
            .foregroundStyle(Color.secondary)
                                        Text(String(describing: conv.protocolLabel))
            .font(.caption)
            .foregroundStyle(Color.secondary)
                                    }
            .padding(8)
                            }
                            .buttonStyle(.plain)
                        }
                } header: {
                    Text("Conversations")
                }
                Section {
                    HStack(alignment: .top, spacing: 8) {
                            HStack(alignment: .top, spacing: 8) {
                                Text("Transport status")
            .font(.caption)
            .foregroundStyle(Color.secondary)
                                Spacer()
                                Button {
                                    eventSink("refreshStatus")
                                } label: {
                                        Text("Refresh")
                                }
            .buttonStyle(.bordered)
                            }
                    }
                    HStack(alignment: .top, spacing: 8) {
                            Text(String(describing: context.matrixStatusLine))
            .font(.caption)
            .foregroundStyle(Color.secondary)
                    }
                    HStack(alignment: .top, spacing: 8) {
                            Text(String(describing: context.stalwartStatusLine))
            .font(.caption)
            .foregroundStyle(Color.secondary)
                    }
                } header: {
                    Text("Protocols")
                }
            }
            .listStyle(.sidebar)
        } detail: {
            VStack(alignment: .leading, spacing: 0) {
                VStack(alignment: .leading, spacing: 4) {
                    Text(String(describing: context.recipientTitle))
            .font(.callout)
            .fontWeight(.semibold)
                    Text(String(describing: context.protocolSummary))
            .font(.caption)
            .foregroundStyle(Color.secondary)
                }
            .padding(12)
            .overlay(alignment: .bottom) {
                Rectangle()
                    .fill(Color(nsColor: .controlBackgroundColor))
                    .frame(height: 1)
            }
                ScrollView {
VStack(alignment: .leading, spacing: 8) {
                        if context.newConversationPrompt {
                            VStack(alignment: .leading, spacing: 4) {
                                Text("Pick Matrix or Stalwart below to start messaging.")
            .font(.callout)
                            }
            .padding(12)
            .background(RoundedRectangle(cornerRadius: 8, style: .continuous).fill(Color(nsColor: .underPageBackgroundColor)))
                        } else {
                            EmptyView()
                        }

                        ForEach(Array(context.messages.enumerated()), id: \.offset) { _, m in
                                if m.isOutgoing {
                                    HStack(alignment: .top, spacing: 8) {
                                        Spacer()
                                        VStack(alignment: .leading, spacing: 4) {
                                            Text(String(describing: m.body))
            .font(.callout)
            .foregroundStyle(Color.white)
                                            Text(String(describing: m.metaLine))
            .font(.caption)
            .foregroundStyle(Color.white)
                                        }
            .padding(12)
            .background(RoundedRectangle(cornerRadius: 8, style: .continuous).fill(Color.clear))
                                    }
                                } else {
                                    HStack(alignment: .top, spacing: 8) {
                                        VStack(alignment: .leading, spacing: 4) {
                                            Text(String(describing: m.body))
            .font(.callout)
                                            Text(String(describing: m.metaLine))
            .font(.caption)
            .foregroundStyle(Color.secondary)
                                        }
            .padding(12)
            .background(RoundedRectangle(cornerRadius: 8, style: .continuous).fill(Color(nsColor: .underPageBackgroundColor)))
                                        Spacer()
                                    }
                                }

                            }
                    }
                }
            .padding(16)
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
                VStack(alignment: .leading, spacing: 8) {
                    Picker("", selection: Binding(get: { context.selectedProtocol }, set: { eventSink("bind:selectedProtocol:\($0)") })) {
                        Text("Matrix").tag("matrix")
                        Text("Stalwart").tag("stalwart")
                        Text("Bitchat").tag("bitchat")
}
                    .pickerStyle(.segmented)
            .padding(.bottom, 4)
                    if context.bitchatSendBlocked {
                        Text("Bitchat is view-only in this build.")
            .font(.caption)
            .foregroundStyle(Color.secondary)
                    } else {
                        EmptyView()
                    }

                    HStack(alignment: .top, spacing: 8) {
                        TextField("iMessage", text: Binding(get: { context.draft }, set: { eventSink("bind:draft:\($0)") }))
            .textFieldStyle(.roundedBorder)
                        Button {
                            eventSink("send")
                        } label: {
                                Text("Send")
                        }
            .buttonStyle(.borderedProminent)
                    }
                }
            .padding(12)
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }
}
